### ISSUE TITLE
`ValidatorOpts` does not implement `status` parameter

### ISSUE THREAD

**Issue by pinebit** [attestantio/go-eth2-client#103]
In according to [the spec](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getStateValidators), `/eth/v1/beacon/states/{state_id}/validators` query provides `id` and `status` arrays. However, the current implementation ignores `status` 
https://github.com/attestantio/go-eth2-client/blob/master/api/validatorsopts.go#L19

Would it be possible and easy to make it matching the spec?

**Comment by mcdee** [comment]
There was a PR #78 that added this, but it needs to be rebased against current master before continuing.  Not sure if the owner of that PR is still interested in the functionality or not.

**Comment by mcdee** [comment]
This has been added to latest master.
