### ISSUE TITLE
`prysmgrpc` doesn't implement `SignedBeaconBlockProvider`

### ISSUE THREAD

**Issue by moshe-blox** [attestantio/go-eth2-client#11]
The `SignedBeaconBlockProvider` interface was recently changed to return `*spec.VersionedSignedBeaconBlock` instead of `*spec.SignedBeaconBlock`.

The `http` package implements this change, but `prysmgrpc` still implements the previous interface.

How can we call `SignedBeaconBlock when connected to Prysm? Or is this still a work in progress?

Thanks!

**Comment by moshe-blox** [comment]
I've forked & updated `prysmgrpc` to implement this change, but without support for Altair (unlike the `http` package). This allows me to keep using the interface without resorting to type assertions.

Please let me know if this makes sense as a pull request.

**Comment by mcdee** [comment]
With prysm implementing the standard HTTP API we're moving away from the `prysmgrpc` module and using `http` instead.  We expect this to be fully available in advance of the mainnet Altair upgrade.

**Comment by moshe-blox** [comment]
That makes sense, thanks!
