### ISSUE TITLE
Slice of pointers can json unmarshal with nil values

### ISSUE THREAD

**Issue by jtraglia** [attestantio/go-eth2-client#113]
Hi there. When unmarshaling structures with a slice of pointers, we do not check that the values are not nil. Therefore, it's possible for these values to be nil after unmarshaling and no error is reported. Depending on how the result is used, this could result in a nil dereference error. This is a pretty common pattern here, but for example, this structure:

https://github.com/attestantio/go-eth2-client/blob/e06a551a82ec98acb92d92a83e659bd3e710563c/api/v1/deneb/blindedbeaconblockbody_json.go#L34-L38

When unmarshaling, we only check if the slice is nil, not the values:

https://github.com/attestantio/go-eth2-client/blob/e06a551a82ec98acb92d92a83e659bd3e710563c/api/v1/deneb/blindedbeaconblockbody_json.go#L105-L108

One potential solution would to make these non-pointer types. Why are these pointers? The other solution would be to add the necessary nil checks when unmarshaling, which could be a lot of work.

**Comment by mcdee** [comment]
Addressed in 595a7a67cfb9ed66c382d0f8ed037acbba7084e4
