### ISSUE TITLE
SignedBeaconBlock execution_payload: data_gas_used: missing

### ISSUE THREAD

**Issue by ink-web3** [attestantio/go-eth2-client#127]
when i call the method SignedBeaconBlock
it returns a error  "execution_payload: data_gas_used: missing"

i test it on  holesky testnet

the beacon rpc url  is  https://ethereum-holesky-beacon-api.publicnode.com

to use the explore to visit https://ethereum-holesky-beacon-api.publicnode.com/eth/v2/beacon/blocks/head ,
i can get response :
`
  "version": "deneb",
  "execution_optimistic": false,
  "finalized": false,
  "data": {
    "message": {
      "slot": "1352018",
      "proposer_index": "784852",
      "parent_root": "0x3ab60a529bbd4b8ab8b023254aae2ac2bb6457436573197b01f80fea28699443",
      "state_root": "0x20f71c36054ec8a5d5277a048e655e4078716cd88e04c23c31871ddcd0aed1dc",
      "body": {
        "randao_reveal": "0xb7714c23d795ad6b506481ef27f5c52c6e66d450ebcee9587630121dedd1732a9ec91b483003f575816e873efb191cd319e881270e30996c5de6090f486d6634c5da601a7cdbe3fd9a97990f55a7f8300567d6b76bec3620e35487d32fc03056",
        "eth1_data": {
          "deposit_root": "0xac676ad4f99c4a4a9b8f65c67630c9e85deda0561360e64e781a232d5820d1eb",
          "deposit_count": "220428",
          "block_hash": "0x316b29d2420bede752600e76320948d31140fbdd6ee7b1437213d82d4cde4f53"
        },
        "graffiti": "0x4c6f6465737461722d76312e31372e302f646566323661630000000000000000",
        "proposer_slashings": [],
        "attester_slashings": [],
        "attestations": [
          {
            "aggregation_bits": "0xfffdfffffbfbebffbfffffff7ffff77deffeffffffffffffffefffffffffffffffffbfffdfff7f7ffd7b7ffffff7ffafefbfedfbf7ffffffbffffff6fffbe3dff7ffefffffffdfffefffffffffffffffffefdfffffffffffdffffeffffe7feffff",
            "data": {
              "slot": "1352017",
              "index": "39",
              "beacon_block_root": "0x3ab60a529bbd4b8ab8b023254aae2ac2bb6457436573197b01f80fea28699443",
              "source": {
                "epoch": "42249",
                "root": "0xc4e30f043471d7dbfd17c31c33a231c0ebb8d58deafaae07c1074e49e2345ace"
              },
              "target": {
                "epoch": "42250",
                "root": "0x8e92051bfad40e14d9dfdbc174a613dadc3bec4ded79e4435f0edbec6afd0cde"
              }
            },
            "signature": "0x876c0faf71892d643549559ad8b713ae53d44b23dbb5b4c56c57714e2d98c6cd340efe19ce98d96cb58a69b6dea7d7d215f3cc156e2cf2c2ef39252d81ca8a3b617109cc922d73cdfd879c42c8b3a12e19441945f860f9c5ea4d341d25994150"
          },`

the response is really  not include "data_gas_used" 

how can i do to fix the problem

ps：
go-eth2-client version： 0.17.3

**Comment by mcdee** [comment]
You need to upgrade to a later version of go-eth2-client; current version is v0.21.1
