### ISSUE TITLE
Failed to parse Quicknode's url

### ISSUE THREAD

**Issue by XWJACK** [attestantio/go-eth2-client#132]
https://www.quicknode.com/docs/ethereum#disabling-token-authentication

**Comment by mcdee** [comment]
I can address this, however quicknode is missing some API endpoints that are required for the connection to operate correctly.  Notably, without the `eth/v1/node/syncing` endpoint the connection won't be able to understand the state of the endpoint and so won't be able to complete the connection.

**Comment by mcdee** [comment]
After some testing it looks like the endpoint does exist, so this can be supported.  However, the endpoint does not appear to be documented so it may be unofficial.  I will put in a fix to support this as much as we can.

**Comment by mcdee** [comment]
This has been addressed in https://github.com/attestantio/go-eth2-client/commit/5ee6799a808df9f9549b9fcd8f0d4c504f2042ce

**Comment by XWJACK** [comment]
It works, thanks for help
