### ISSUE TITLE
Slashing events

### ISSUE THREAD

**Issue by kaber2** [attestantio/go-eth2-client#149]
I would like to track validator joins and exists, however it appears that currently none of the slashing events are supported. Is there a reason for this, or did you just not get around to add them so far?

Thanks!

**Comment by mcdee** [comment]
These are recent additions to the spec, so they can be added but there needs to be a check against the consensus clients to confirm they support these events.

**Comment by kaber2** [comment]
Thanks for your response. Regarding that check against the clients, at least prysm appears to reject subscriptions to unsupported event types. I would assume this is pretty much all a client can do, try and propagate any error returned, which obviously needs to happen anyway. Do you have something else in mind?

**Comment by mcdee** [comment]
Historically there have been issues with the format of the data in the events, so it's worth creating slashing events (on a testnet, obviously) and catching the output from all of the clients to ensure conformity.

**Comment by kaber2** [comment]
Well, that definitely exceeds the time I'm willing to allocate to this.

I would argue that this would be a bug in the clients implementation and in case it actually does exist, any user who runs into it can report it to both the client to get fixed, and to this package for a workaround.

**Comment by mcdee** [comment]
These events have now been added to master.
