### ISSUE TITLE
Error: invalid value for inactivity score

### ISSUE THREAD

**Issue by alrevuelta** [attestantio/go-eth2-client#15]
I'm getting an error `invalid value for inactivity score` from time to time. A bit odd since this value should be zero unless the network hits non-finality. However I haven't managed to reproduce it, it appears every 30 minutes with an Infura endpoint.

On the other hand, shouldn't `ParseUint` use `64` [here](https://github.com/attestantio/go-eth2-client/blob/master/spec/altair/beaconstate.go#L319), since its a `uint64` type according to the [spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/beacon-chain.md#beaconstate)? Not sure if this is the issue though.

Some of the errors I got:

```
failed to parse altair beacon state: invalid value for inactivity score 0: strconv.ParseUint: parsing \"1600\": value out of range"
failed to parse altair beacon state: invalid value for inactivity score 0: strconv.ParseUint: parsing \"1612\": value out of range"
failed to parse altair beacon state: invalid value for inactivity score 0: strconv.ParseUint: parsing \"1640\": value out of range"
failed to parse altair beacon state: invalid value for inactivity score 0: strconv.ParseUint: parsing \"1712\": value out of range"
failed to parse altair beacon state: invalid value for inactivity score 0: strconv.ParseUint: parsing \"1732\": value out of range"
failed to parse altair beacon state: invalid value for inactivity score 0: strconv.ParseUint: parsing \"1732\": value out of range"
failed to parse altair beacon state: invalid value for inactivity score 0: strconv.ParseUint: parsing \"1820\": value out of range"
```

I will update as soon as I get more.

**Comment by mcdee** [comment]
Good spot; tagged `v0.10.1` with a fix for this.
