### ISSUE TITLE
Chain ID?

### ISSUE THREAD

**Issue by jbrower95** [attestantio/go-eth2-client#150]
Curious if you know the solution here--

- I want to check that a beacon RPC corresponds to the same chainID as some other execution node.
- How do I check which execution ChainID this beacon chain is relevant to?

Thanks!

**Comment by mcdee** [comment]
Consensus nodes do not have chain ID, but there is information in the `Genesis()` call that can be used to make a 1:1 mapping from this information to the execution chain ID.
