### ISSUE TITLE
Production code is using debug endpoints

### ISSUE THREAD

**Issue by KaloyanTanev** [attestantio/go-eth2-client#158]
In the validators file, there is a call to [fetch all validators](https://github.com/attestantio/go-eth2-client/blob/50179b8bd4d75c956248c8af698373fac1ddb6c9/http/validators.go#L56) from beacon state if neither PKs or indices are supplied. Then this function calls the `BeaconState` function, which sends a request [to debug endpoint](https://github.com/attestantio/go-eth2-client/blob/50179b8bd4d75c956248c8af698373fac1ddb6c9/http/beaconstate.go#L50).

This shouldn't be used in production code, instead the [proper v1 endpoint for this](https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidators) should be put into use.

**Comment by mcdee** [comment]
Having `debug` in the endpoint is a misnomer nowadays, this namespace is enabled by default in all major beacon node implementations and the only reason that the endpoint wasn't moved to a non-debug namespace was the effort involved in migration.
