### ISSUE TITLE
Incorrect JSON field name

### ISSUE THREAD

**Issue by nyunyunyunyu** [attestantio/go-eth2-client#28]
https://github.com/attestantio/go-eth2-client/blob/9404ab6af6f02d9da5be5cbc29c79d82ae7ffb19/api/v1/blindedbeaconblockbody.go#L55

The filed name should be "execution_payload".

**Comment by mcdee** [comment]
The specification at https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/produceBlindedBlock states that this should be `execution_payload_header`, where are you seeing otherwise?

**Comment by nyunyunyunyu** [comment]
You are right. Sry I totally misunderstood the struct... This is dumb.
