### ISSUE TITLE
Keep url prefix when calling events api

### ISSUE THREAD

**Issue by alex88** [attestantio/go-eth2-client#29]
When using an url like this one https://domain/prefix/ all the requests I've tested work fine except for the events one which replaces the path with the `/eth/v1/events` one.

Probably because the other GET/POST requests [append](https://github.com/attestantio/go-eth2-client/blob/master/http/http.go#L46) the request url to the basepath compared to the events one which uses [resolveReference](https://github.com/attestantio/go-eth2-client/blob/master/http/events.go#L51) which replaces the path since the events endpoint starts with a `/`

**Comment by mcdee** [comment]
Thank you for reporting this issue.  A fix is available at #30  please could you try this out and confirm if it addresses the problem?

**Comment by alex88** [comment]
Thanks @mcdee, the fix worked! Sorry for the delay
