### ISSUE TITLE
Zerolog logger isn't threadsafe

### ISSUE THREAD

**Issue by corverroos** [attestantio/go-eth2-client#31]
We cannot run our tests with `-race` since it detects a race inside go-eth2-client. This is due to the use of a global `zerolog.Logger` that is not threadsafe. This global logger is used concurrently in the `http` package.

To reproduce, run: `go test -race ./...` in this repo.

**Comment by corverroos** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/29249923/192273602-2e828779-3e9a-44c0-bc72-0ff3d34ed6f7.png">

**Comment by mcdee** [comment]
This has been on the TODO list for a while, I'll dig out my old branch with this on and see if I can fix it up.

**Comment by corverroos** [comment]
Thanks! Yeah it is weird that the zerolog logger isn't threadsafe 😞

**Comment by mcdee** [comment]
Please can you take a look at #32 and see if it addresses your issue?

**Comment by corverroos** [comment]
Awesome thanks approved 🙏
