### ISSUE TITLE
Capella SignedBlindedBeaconBlock missing ssz&tests

### ISSUE THREAD

**Issue by olegshmuelov** [attestantio/go-eth2-client#50]
Any ETA for implementing/generating ssz/test/yaml/json for [Capella SignedBlindedBeaconBlock](https://github.com/attestantio/go-eth2-client/blob/bc14358487b6d32cb45feef14b170458abc5d14a/api/v1/capella/signedblindedbeaconblock.go#LL1)

as for now latest v0.15.7 version does not cover it.

**Comment by mcdee** [comment]
I have added in suitable tests, broken out the files suitably, and regenerated the SSZ with the latest `sszgen`.
