### ISSUE TITLE
Corrupted "Good" Capella beacon block data

### ISSUE THREAD

**Issue by olegshmuelov** [attestantio/go-eth2-client#54]
The ["Good"](https://github.com/attestantio/go-eth2-client/blob/97e8ba2594740787513f2450a842e8bd617c1f1e/spec/capella/beaconblock_test.go#LL133C1-L133C1) test beacon block data
have incorrect size for some of the body.deposits proofs

instead of 32 bytes the test proof data has 33 bytes.
e.g `"0x000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"` --> 33 bytes

How to reproduce:
1. Marshal SSZ the block
2. Fail on Unmarshal

saw the issue for Capella block, but could happen to all other versions as well

**Comment by mcdee** [comment]
Turns out this was an error in some initial test data way back in phase 0 that has been propagated since then.  Apologies for the delay, but have now found the issue and will send in a fix soon.  Thanks for reporting!
