### ISSUE TITLE
Extraneous debug.PrintStack creates extra log lines

### ISSUE THREAD

**Issue by djoyahoy** [attestantio/go-eth2-client#6]
https://github.com/attestantio/go-eth2-client/blob/60424f2661410160c302b508d16fd2af66eca0f5/prysmgrpc/helpers.go#L130

There is a debug.PrintStack linked above that may not be necessary. Can it be removed?

**Comment by mcdee** [comment]
Thank you for reporting this issue.  The offending line has been removed in 31de72f and release 0.6.30 tagged.
