### ISSUE TITLE
Enable TLS communication for Prysm gRPC

### ISSUE THREAD

**Issue by amir-blox** [attestantio/go-eth2-client#8]
gRPC client is configured with insecure transport and therefore makes it impossible to interact with nodes over `TLS` 

https://github.com/attestantio/go-eth2-client/blob/a7129eecd62a309e6a934c39023833331e4459a3/prysmgrpc/service.go#L89

**Comment by BisonDee** [comment]
Funny enough, we were just working with this and I was about to open an issue. :)
Risking overloading the request here, but it would additionally be great to have a configuration option to add basic auth. Typically this would be a simple "WithHeaders" sort of thing, but with the Go GRPC implementation, it requires an interface. Yay.

**Comment by mcdee** [comment]
@amir-blox I will take a look at this, however prysm is looking to fully implement the standard HTTP API, at which point I will most likely deprecate the grpc connection.

@BisonDee I am unaware of any of the standard HTTP API providers that have an option for authentication.  Where would you look to use this?

**Comment by BisonDee** [comment]
> @BisonDee I am unaware of any of the standard HTTP API providers that have an option for authentication. Where would you look to use this?

Morning. Adding basic auth headers was in reference to the gRPC connection (along with TLS).  We have Prysm behind a proxy using TLS and basic auth. That being said we are now just using Lighthouse's beacon node API (and this go-eth2-client).

In general the gRPC API has been difficult to work with in many dimensions and would welcome a move to the standard HTTP API.

**Comment by mcdee** [comment]
@BisonDee given the detail so far I'm assuming that per-connection headers passed in to the service will be sufficient, rather than per-request headers.  Does this sound okay to you?

**Comment by mcdee** [comment]
@BisonDee Alternatively, it is possible to pass in your own context to each request that included the headers you wished to provide.  This would give you more flexibility, and avoid changes to the prysmgrpc codebase.  May this be a better approach?

**Comment by BisonDee** [comment]
Thanks @mcdee - Context passing is totally cool and sounds easy enough to use.

**Comment by mcdee** [comment]
@amir-blox There is now a `tls` branch that contains the ability to create a TLS connection, along with options to use client and CA certs if required.  Please could you give it a go and see if it does what you need?

@BisonDee you can create a new context for requests with headers, along the lines of:

```
import "google.golang.org/grpc/metadata"
...
md := metadata.New(map[string]string{"Authorization","Bearer token"})
ctx = metadata.NewOutgoingContext(ctx, md)
```

and if you supply that context to the call it should post them.

**Comment by mcdee** [comment]
@amir-blox any feedback on the TLS changes?

@BisonDee does the code above solve your issue?

**Comment by BisonDee** [comment]
Thanks Jim, I think this would work just fine. Appreciated. Any mechanism that allows for these headers over the connection is great.

**Comment by BisonDee** [comment]
Just wanted to circle back on this. I have written scripts against this branch and successfully connected to a Prysm Beacon API using TLS and the metadata.

For the client, it only required this:
```
prysmParameters := make([]prysmgrpc.Parameter, 0)
prysmParameters = append(prysmParameters, prysmgrpc.WithAddress(prysmURL))
prysmParameters = append(prysmParameters, prysmgrpc.WithTLS(true))
client, err := prysmgrpc.New(ctx, prysmParameters...)
```

And for the authenticated call:
```
md := metadata.New(map[string]string{"Authorization": fmt.Sprintf("Basic %s", basicAuth(username, password))})
ctx = metadata.NewOutgoingContext(context.Background(), md)
```

One quirk unrelated to this library is that the context cannot be passed into a function for some reason. I had to create this context in each function that called out.

**Comment by mcdee** [comment]
Thanks for the update, I'll sort out a release with these changes.

**Comment by mcdee** [comment]
Tagged release v0.7.2 with this functionality.
